# fly.toml - AzuraCast on Fly.io | EstacionKusMediaos
# Generado para: luisitoys12/azuracast-flyio

app = 'azuracast-kusmediao'
primary_region = 'dal'

[build]
  image = 'ghcr.io/luisitoys12/azuracast-flyio:main'

[http_service]
  internal_port = 80
  force_https = true
  auto_stop_machines = false
  auto_start_machines = true
  min_machines_running = 1

[[vm]]
  cpu_kind = 'shared'
  cpus = 2
  memory_mb = 2048

[[mounts]]
  source = 'azuracast_data'
  destination = '/var/azuracast'

# Puerto streaming Icecast/Liquidsoap
[[services]]
  protocol = 'tcp'
  internal_port = 8000

  [[services.ports]]
    port = 8000

# Puerto admin stats
[[services]]
  protocol = 'tcp'
  internal_port = 8090

  [[services.ports]]
    port = 8090
