app = 'azuracast-flyio'
primary_region = 'iad'

[build]
  dockerfile = "Dockerfile"

[processes]
  app = "/usr/local/bin/my_init --no-main-command"

[[mounts]]
  source = 'azuracast'
  destination = '/var/azuracast'

[[services]]
  internal_port = 80
  protocol = "tcp"
  processes = ["app"]

  [[services.ports]]
    port = 80
    handlers = ["http"]
    force_https = true

  [[services.ports]]
    port = 443
    handlers = ["tls", "http"]

  [services.concurrency]
    type = "connections"
    hard_limit = 100
    soft_limit = 80

[[services]]
  internal_port = 8000
  protocol = "tcp"
  processes = ["app"]

  [[services.ports]]
    port = 8000

[[services]]
  internal_port = 8443
  protocol = "tcp"
  processes = ["app"]

  [[services.ports]]
    port = 8443

[[services]]
  internal_port = 2022
  protocol = "tcp"
  processes = ["app"]

  [[services.ports]]
    port = 2022

[[vm]]
  memory = '2048mb'
  cpus = 2
  cpu_kind = 'shared'
